name: RUNNER
on:
  workflow_dispatch:
      
jobs:
  run-files:
    runs-on:
      group: group1
      labels: rt2
    strategy:
      matrix:
        job-name: [t0,t1,t2,t3,t4,t5,t6,t7,t8,t9]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4


      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          java -jar w11a.jar
